### PR TITLE
Remove unwanted folders in build

### LINKED ISSUE #44: Clean-up npm package
Here's the output of `npm publish --dry-run`

```
npm notice
npm notice 📦  @openzim/libzim@2.2.5
npm notice === Tarball Contents ===
npm notice 1.5kB   package.json
npm notice 4.1kB   .clang-format
npm notice 21B     .env
npm notice 2.2kB   binding.gyp
npm notice 1.2kB   bundle-libzim.js
npm notice 275B    Changelog
npm notice 543B    CPPLINT.cfg
npm notice 2.0kB   download-libzim.js
npm notice 359B    jest.config.js
npm notice 35.1kB  LICENSE
npm notice 2.3kB   README.md
npm notice 281B    tsconfig.json
npm notice 853B    tslint.json
npm notice 677B    .github/FUNDING.yml
npm notice 119B    build/binding.Makefile
npm notice 23.4kB  build/gyp-mac-tool
npm notice 13.5kB  build/Makefile
npm notice 3.0kB   build/Release/.deps/Release/obj.target/zim_binding/src/article.o.d
npm notice 3.6kB   build/Release/.deps/Release/obj.target/zim_binding/src/module.o.d
npm notice 3.5kB   build/Release/.deps/Release/obj.target/zim_binding/src/reader.o.d
npm notice 3.0kB   build/Release/.deps/Release/obj.target/zim_binding/src/writer.o.d
npm notice 621B    build/Release/.deps/Release/zim_binding.node.d
npm notice 15.7MB  build/Release/libzim.6.dylib
npm notice 693.0kB build/Release/obj.target/zim_binding/src/article.o
npm notice 178.0kB build/Release/obj.target/zim_binding/src/module.o
npm notice 535.6kB build/Release/obj.target/zim_binding/src/reader.o
npm notice 539.0kB build/Release/obj.target/zim_binding/src/writer.o
npm notice 148.2kB build/Release/zim_binding.node
npm notice 5.9kB   build/zim_binding.target.mk
npm notice 167B    dist/index.d.ts
npm notice 321B    dist/index.js
npm notice 139B    dist/zim.d.ts
npm notice 547B    dist/zim.js
npm notice 791B    dist/ZimCreator.d.ts
npm notice 7.9kB   dist/ZimCreator.js
npm notice 402B    dist/ZimReader.d.ts
npm notice 5.3kB   dist/ZimReader.js
npm notice 8.1kB   src/article.cc
npm notice 3.9kB   src/article.h
npm notice 323B    src/module.cc
npm notice 3.4kB   src/reader.cc
npm notice 916B    src/reader.h
npm notice 1.9kB   src/writer.cc
npm notice 953B    src/writer.h
npm notice === Tarball Details ===
npm notice name:          @openzim/libzim
npm notice version:       2.2.5
npm notice package size:  7.2 MB
npm notice unpacked size: 18.0 MB
npm notice shasum:        67b3ea6d163119d81467f947682a6a8020ada545
npm notice integrity:     sha512-W2Ubwk0OwY1sN[...]3O+nfa5gGyBEA==
npm notice total files:   45
```

As you can see, it contains a lot of files that probably shouldn't be submitted: all of the `build` folder for instance (maybe others).
This is all present in the current online package as can be verified with `npm pack @openzim/libzim`

### PR DESCRIPTION
**Pull request by bakshiutkarsha**
should resolve #44

### CODE REVIEW

**Comment by kelson42** [comment]
Can you please publish here the listing of the npm package content (filenames)?

**Comment by bakshiutkarsha** [comment]
> Can you please publish here the listing of the npm package content (filenames)?

```
> @openzim/libzim@2.2.5 prepare .
> npm run tsc


> @openzim/libzim@2.2.5 tsc /Users/Utkarsha/Documents/Projects/node-libzim
> tsc

npm notice
npm notice 📦  @openzim/libzim@2.2.5
npm notice === Tarball Contents ===
npm notice 4.1kB  .clang-format      
npm notice 21B    .env                
npm notice 275B   Changelog          
npm notice 35.1kB LICENSE            
npm notice 8.1kB  src/article.cc      
npm notice 323B   src/module.cc      
npm notice 3.4kB  src/reader.cc      
npm notice 1.9kB  src/writer.cc      
npm notice 543B   CPPLINT.cfg        
npm notice 2.2kB  binding.gyp        
npm notice 3.9kB  src/article.h      
npm notice 916B   src/reader.h        
npm notice 953B   src/writer.h        
npm notice 1.2kB  bundle-libzim.js    
npm notice 2.0kB  download-libzim.js  
npm notice 321B   dist/index.js      
npm notice 359B   jest.config.js      
npm notice 547B   dist/zim.js        
npm notice 7.9kB  dist/ZimCreator.js  
npm notice 5.3kB  dist/ZimReader.js  
npm notice 1.5kB  package.json        
npm notice 281B   tsconfig.json      
npm notice 853B   tslint.json        
npm notice 2.3kB  README.md          
npm notice 167B   dist/index.d.ts    
npm notice 139B   dist/zim.d.ts      
npm notice 791B   dist/ZimCreator.d.ts
npm notice 402B   dist/ZimReader.d.ts
npm notice 677B   .github/FUNDING.yml
npm notice === Tarball Details ===
npm notice name:          @openzim/libzim                        
npm notice version:       2.2.5                                  
npm notice package size:  25.3 kB                                
npm notice unpacked size: 86.5 kB                                
npm notice shasum:        95052899664c9e3ecc55069446523f321e29984b
npm notice integrity:     sha512-UZutsmDGzZDN/[...]0F7POy3marIVQ==
npm notice total files:   29                                      
npm notice
+ @openzim/libzim@2.2.5
```

Let me know if any other file also needs to be removed.

**Comment by kelson42** [comment]
Please remove everything which is not necessary to run the node-libzim.

**Comment by bakshiutkarsha** [comment]
Some of the files I have manually removed and tested after running node-libzim. I still need confirmation on these once although the checks were passed after publishing it locally. @kelson42 

```
.github/FUNDING.yml
.clang-format
CPPLINT.cfg
tslint.json
.env
```

Also, the following paths and files are never ignored, so adding them to .npmignore is not required:

```
package.json
README (and its variants)
CHANGELOG (and its variants)
LICENSE / LICENCE
```

**Comment by kelson42** [comment]
@bakshiutkarsha I hardly see how `.env` would not be required as this is necessary to know which version of the libzim to download. Everything in `.github` should be ignored.

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha I hardly see how `.env` would not be required as this is necessary to know which version of the libzim to download. Everything in `.github` should be ignored.

Sorry my bad, `.env `shouldn't be there, must have missed it.

**Pull request merged**
